// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PQM.Infrastructure;

#nullable disable

namespace PQM.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260723063947_AddDeviceEventsMapping")]
    partial class AddDeviceEventsMapping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PQM.Core.Entities.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthenticationTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("ClientAddress")
                        .HasColumnType("int");

                    b.Property<string>("ConsumerNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedId")
                        .HasColumnType("int");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IP");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastConnectionAttempt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastSync")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MeterTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PORT")
                        .HasColumnType("int")
                        .HasColumnName("PORT");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ServerAddress")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeZoneId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Timeout")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("PQM.Core.Entities.DeviceConnectionEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("DeviceConnectionEvents");
                });

            modelBuilder.Entity("PQM.Core.Entities.DeviceEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int>("EventCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParameterId")
                        .HasColumnType("int");

                    b.Property<string>("RawClock")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReadTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("ParameterId");

                    b.ToTable("DeviceEvent", (string)null);
                });

            modelBuilder.Entity("PQM.Core.Entities.DeviceLatestReading", b =>
                {
                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int>("ParameterId")
                        .HasColumnType("int");

                    b.Property<string>("RawValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeviceId", "ParameterId");

                    b.HasIndex("ParameterId");

                    b.ToTable("DeviceLatestReadings", (string)null);
                });

            modelBuilder.Entity("PQM.Core.Entities.DeviceParameterConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ParameterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DeviceParameterConfig");
                });

            modelBuilder.Entity("PQM.Core.Entities.DeviceProfileSyncState", b =>
                {
                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<int?>("LastReadEntryIndex")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastReadTimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DeviceId", "ProfileId");

                    b.HasIndex("ProfileId");

                    b.ToTable("DeviceProfileSyncState", (string)null);
                });

            modelBuilder.Entity("PQM.Core.Entities.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int>("ParameterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("PQM.Core.Entities.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Attribute3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AttributeIndex")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedId")
                        .HasColumnType("int");

                    b.Property<string>("DataType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHistorical")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObisCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<int?>("Scaler")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Parameters", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 663, DateTimeKind.Utc).AddTicks(9189),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Accuracy Test Start",
                            ObisCode = "0.128.162.0.128.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1720),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Accuracy Test Stop",
                            ObisCode = "0.128.162.1.128.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1725),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Activity Calendar",
                            ObisCode = "0.0.13.0.0.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1727),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Apparent Power – kVA",
                            ObisCode = "1.0.9.7.0.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1842),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Association LN Meter Reader",
                            ObisCode = "0.0.40.0.2.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1844),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Available Billing Periods",
                            ObisCode = "0.0.0.1.1.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1863),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Billing Date",
                            ObisCode = "0.0.0.1.2.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1865),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Billing Period Script Table",
                            ObisCode = "0.0.10.0.1.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1866),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Capture Period of Daily Load Profile",
                            ObisCode = "1.0.0.8.5.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1868),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Category",
                            ObisCode = "0.0.94.91.11.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1870),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "CMRI Reset",
                            ObisCode = "0.128.154.128.128.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1871),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "CT Rating",
                            ObisCode = "0.0.94.91.12.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1873),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Cumulative Billing Count",
                            ObisCode = "0.0.0.1.0.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1875),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Cumulative Energy – kVAh (Export)",
                            ObisCode = "1.0.10.8.0.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1877),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Cumulative Energy (kVAh)",
                            ObisCode = "1.0.9.8.0.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1879),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Cumulative Energy (kvarh) – Lag",
                            ObisCode = "1.0.5.8.0.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1880),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Cumulative Energy (kvarh) – Lead",
                            ObisCode = "1.0.8.8.0.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1882),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Cumulative Energy (kWh)",
                            ObisCode = "1.0.1.8.0.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1884),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Cumulative Energy (kWh) – Export",
                            ObisCode = "1.0.2.8.0.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1886),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Cumulative Power Failure Duration",
                            ObisCode = "0.0.94.91.8.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1905),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Cumulative Programming Count",
                            ObisCode = "0.0.96.2.0.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1907),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Cumulative Tamper Count",
                            ObisCode = "0.0.94.91.0.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1909),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Current – IB",
                            ObisCode = "1.0.71.7.0.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1910),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Current – IR",
                            ObisCode = "1.0.31.7.0.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1912),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Current – IY",
                            ObisCode = "1.0.51.7.0.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1914),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Current Related Event Code",
                            ObisCode = "0.0.96.11.1.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1916),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Power Failure Related Event Code",
                            ObisCode = "0.0.96.11.2.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1917),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Profile Capture Period",
                            ObisCode = "1.0.0.8.4.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1919),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "PT Power Fail Tamper Events",
                            ObisCode = "1.0.128.7.90.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1921),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Reset Type",
                            ObisCode = "0.128.153.128.128.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1923),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Signed Active Power – kW",
                            ObisCode = "1.0.1.7.0.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1924),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Signed Power Factor – B Phase",
                            ObisCode = "1.0.73.7.0.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1926),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Signed Power Factor – R Phase",
                            ObisCode = "1.0.33.7.0.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1928),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Signed Power Factor – Y Phase",
                            ObisCode = "1.0.53.7.0.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1930),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Signed Reactive Power – kvar",
                            ObisCode = "1.0.3.7.0.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1931),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Single Action Schedule for Billing Dates",
                            ObisCode = "0.0.15.0.0.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1934),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "TCP/UDP Setup",
                            ObisCode = "0.0.25.0.0.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1936),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "TCP/UDP Setup IPv4 Address",
                            ObisCode = "0.0.25.1.0.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1938),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "TCP/UDP Setup MAC Address",
                            ObisCode = "0.0.25.2.0.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1940),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Transaction Related Event Code",
                            ObisCode = "0.0.96.11.3.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1941),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Voltage – VBN",
                            ObisCode = "1.0.72.7.0.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1943),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Voltage – VRN",
                            ObisCode = "1.0.32.7.0.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1945),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Voltage – VYN",
                            ObisCode = "1.0.52.7.0.255",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1946),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Voltage L1",
                            ObisCode = "1.0.32.7.0.251",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1948),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Voltage L2",
                            ObisCode = "1.0.52.7.0.251",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1959),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Current L1",
                            ObisCode = "1.0.31.7.0.251",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1961),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Active Power",
                            ObisCode = "1.0.1.7.0.251",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1962),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Billing Energy",
                            ObisCode = "1.0.9.8.0.251",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1964),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Import Energy",
                            ObisCode = "1.0.1.8.0.251",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1966),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Export Energy",
                            ObisCode = "1.0.2.8.0.251",
                            ProfileId = 0,
                            TypeName = "ABT"
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2026, 7, 23, 6, 39, 43, 664, DateTimeKind.Utc).AddTicks(1968),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            IsHistorical = true,
                            IsVisible = true,
                            Name = "Maximum Demand",
                            ObisCode = "1.0.9.6.0.251",
                            ProfileId = 0,
                            TypeName = "ABT"
                        });
                });

            modelBuilder.Entity("PQM.Core.Entities.ParameterValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int>("ParameterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ParameterValue");
                });

            modelBuilder.Entity("PQM.Core.Entities.Profile", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfileId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObisCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProfileId");

                    b.ToTable("Profiles", (string)null);
                });

            modelBuilder.Entity("PQM.Core.Entities.ReadingSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("DeviceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EntryTimestampUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("EntryTimestampUtc");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReadTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("DeviceId", "ProfileId", "EntryTimestampUtc")
                        .IsUnique()
                        .HasDatabaseName("IX_ReadingSessions_Device_Profile_Timestamp")
                        .HasFilter("[EntryTimestampUtc] IS NOT NULL");

                    b.ToTable("ReadingSessions", (string)null);
                });

            modelBuilder.Entity("PQM.Core.Entities.ReadingValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("ParameterId")
                        .HasColumnType("int");

                    b.Property<string>("RawValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SessionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ValueNumeric")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ParameterId");

                    b.HasIndex("SessionId");

                    b.ToTable("ReadingValues", (string)null);
                });

            modelBuilder.Entity("PQM.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("PQM.Core.Entities.DeviceConnectionEvent", b =>
                {
                    b.HasOne("PQM.Core.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("PQM.Core.Entities.DeviceEvent", b =>
                {
                    b.HasOne("PQM.Core.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PQM.Core.Entities.Parameter", "Parameter")
                        .WithMany()
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Parameter");
                });

            modelBuilder.Entity("PQM.Core.Entities.DeviceLatestReading", b =>
                {
                    b.HasOne("PQM.Core.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PQM.Core.Entities.Parameter", "Parameter")
                        .WithMany()
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Parameter");
                });

            modelBuilder.Entity("PQM.Core.Entities.DeviceProfileSyncState", b =>
                {
                    b.HasOne("PQM.Core.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PQM.Core.Entities.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("PQM.Core.Entities.Parameter", b =>
                {
                    b.HasOne("PQM.Core.Entities.Profile", "Profile")
                        .WithMany("Parameters")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("PQM.Core.Entities.ReadingSession", b =>
                {
                    b.HasOne("PQM.Core.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId");

                    b.HasOne("PQM.Core.Entities.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId");

                    b.Navigation("Device");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("PQM.Core.Entities.ReadingValue", b =>
                {
                    b.HasOne("PQM.Core.Entities.Parameter", "Parameter")
                        .WithMany("ReadingValues")
                        .HasForeignKey("ParameterId");

                    b.HasOne("PQM.Core.Entities.ReadingSession", "Session")
                        .WithMany("Values")
                        .HasForeignKey("SessionId");

                    b.Navigation("Parameter");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("PQM.Core.Entities.Parameter", b =>
                {
                    b.Navigation("ReadingValues");
                });

            modelBuilder.Entity("PQM.Core.Entities.Profile", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("PQM.Core.Entities.ReadingSession", b =>
                {
                    b.Navigation("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
