// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PQM.Infrastructure;

#nullable disable

namespace PQM.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260717113632_ExpandDeviceSchema")]
    partial class ExpandDeviceSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PQM.Core.Entities.ActionSchedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("ExecutionTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObisCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ParameterId")
                        .HasColumnType("int");

                    b.Property<string>("RawValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReadTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ScheduleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScriptName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScriptObisCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Selector")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "ObisCode")
                        .IsUnique();

                    b.ToTable("ActionSchedule");
                });

            modelBuilder.Entity("PQM.Core.Entities.AssociationMetadata", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AssociationStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthenticationMechanism")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientSAP")
                        .HasColumnType("int");

                    b.Property<string>("Conformance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int>("DlmsVersion")
                        .HasColumnType("int");

                    b.Property<int>("MaxReceivePduSize")
                        .HasColumnType("int");

                    b.Property<int>("MaxSendPduSize")
                        .HasColumnType("int");

                    b.Property<string>("ObisCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ParameterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReadTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecuritySetupReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServerSAP")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "ObisCode")
                        .IsUnique();

                    b.ToTable("AssociationMetadata");
                });

            modelBuilder.Entity("PQM.Core.Entities.CalendarData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CalendarNameActive")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CalendarNamePassive")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DayProfileActive")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DayProfilePassive")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("ObisCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ParameterId")
                        .HasColumnType("int");

                    b.Property<string>("RawValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReadTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SeasonProfileActive")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeasonProfilePassive")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeekProfileActive")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeekProfilePassive")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "ObisCode")
                        .IsUnique();

                    b.ToTable("CalendarData");
                });

            modelBuilder.Entity("PQM.Core.Entities.CommunicationValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("FormattedValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObisCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ParameterId")
                        .HasColumnType("int");

                    b.Property<string>("RawValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReadTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "ObisCode")
                        .IsUnique();

                    b.ToTable("CommunicationValue");
                });

            modelBuilder.Entity("PQM.Core.Entities.DLMSObject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AttributeAccessRights")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastReadTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("datetime2");

                    b.Property<string>("MethodAccessRights")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObisCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParameterId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "ObisCode")
                        .IsUnique();

                    b.ToTable("DLMSObject");
                });

            modelBuilder.Entity("PQM.Core.Entities.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Authentication")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClientAddress")
                        .HasColumnType("int");

                    b.Property<string>("ConsumerNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedId")
                        .HasColumnType("int");

                    b.Property<string>("FtpFolder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSync")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PORT")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ServerAddress")
                        .HasColumnType("int");

                    b.Property<int?>("Timeout")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Device");
                });

            modelBuilder.Entity("PQM.Core.Entities.DeviceEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int>("EventCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObisCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParameterId")
                        .HasColumnType("int");

                    b.Property<string>("RawClock")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReadTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DeviceEvent");
                });

            modelBuilder.Entity("PQM.Core.Entities.DeviceLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DeviceLog");
                });

            modelBuilder.Entity("PQM.Core.Entities.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int>("ParameterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("PQM.Core.Entities.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Attribute3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObisCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ObjectType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Scaler")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ObisCode")
                        .IsUnique()
                        .HasFilter("[ObisCode] IS NOT NULL");

                    b.ToTable("Parameter");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Configuration",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Accuracy Test Start",
                            ObisCode = "0.128.162.0.128.255"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Configuration",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Accuracy Test Stop",
                            ObisCode = "0.128.162.1.128.255"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Calendar",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Activity Calendar",
                            ObisCode = "0.0.13.0.0.255"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Power",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Apparent Power – kVA",
                            ObisCode = "1.0.9.7.0.255"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Association",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Association LN Meter Reader",
                            ObisCode = "0.0.40.0.2.255"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Calendar",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Available Billing Periods",
                            ObisCode = "0.0.0.1.1.255"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Calendar",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Billing Date",
                            ObisCode = "0.0.0.1.2.255"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Script",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Billing Period Script Table",
                            ObisCode = "0.0.10.0.1.255"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Configuration",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Capture Period of Daily Load Profile",
                            ObisCode = "1.0.0.8.5.255"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Configuration",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Category",
                            ObisCode = "0.0.94.91.11.255"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Configuration",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "CMRI Reset",
                            ObisCode = "0.128.154.128.128.255"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Configuration",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "CT Rating",
                            ObisCode = "0.0.94.91.12.255"
                        },
                        new
                        {
                            Id = 13,
                            Category = "General",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Cumulative Billing Count",
                            ObisCode = "0.0.0.1.0.255"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Energy",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Cumulative Energy – kVAh (Export)",
                            ObisCode = "1.0.10.8.0.255"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Energy",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Cumulative Energy (kVAh)",
                            ObisCode = "1.0.9.8.0.255"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Energy",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Cumulative Energy (kvarh) – Lag",
                            ObisCode = "1.0.5.8.0.255"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Energy",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Cumulative Energy (kvarh) – Lead",
                            ObisCode = "1.0.8.8.0.255"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Energy",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Cumulative Energy (kWh)",
                            ObisCode = "1.0.1.8.0.255"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Energy",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Cumulative Energy (kWh) – Export",
                            ObisCode = "1.0.2.8.0.255"
                        },
                        new
                        {
                            Id = 20,
                            Category = "General",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Cumulative Power Failure Duration",
                            ObisCode = "0.0.94.91.8.255"
                        },
                        new
                        {
                            Id = 21,
                            Category = "General",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Cumulative Programming Count",
                            ObisCode = "0.0.96.2.0.255"
                        },
                        new
                        {
                            Id = 22,
                            Category = "General",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Cumulative Tamper Count",
                            ObisCode = "0.0.94.91.0.255"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Current",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Current – IB",
                            ObisCode = "1.0.71.7.0.255"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Current",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Current – IR",
                            ObisCode = "1.0.31.7.0.255"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Current",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Current – IY",
                            ObisCode = "1.0.51.7.0.255"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Event",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Current Related Event Code",
                            ObisCode = "0.0.96.11.1.255"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Event",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Power Failure Related Event Code",
                            ObisCode = "0.0.96.11.2.255"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Configuration",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Profile Capture Period",
                            ObisCode = "1.0.0.8.4.255"
                        },
                        new
                        {
                            Id = 29,
                            Category = "Event",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "PT Power Fail Tamper Events",
                            ObisCode = "1.0.128.7.90.255"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Configuration",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Reset Type",
                            ObisCode = "0.128.153.128.128.255"
                        },
                        new
                        {
                            Id = 31,
                            Category = "Power",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Signed Active Power – kW",
                            ObisCode = "1.0.1.7.0.255"
                        },
                        new
                        {
                            Id = 32,
                            Category = "PowerFactor",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Signed Power Factor – B Phase",
                            ObisCode = "1.0.73.7.0.255"
                        },
                        new
                        {
                            Id = 33,
                            Category = "PowerFactor",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Signed Power Factor – R Phase",
                            ObisCode = "1.0.33.7.0.255"
                        },
                        new
                        {
                            Id = 34,
                            Category = "PowerFactor",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Signed Power Factor – Y Phase",
                            ObisCode = "1.0.53.7.0.255"
                        },
                        new
                        {
                            Id = 35,
                            Category = "Power",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Signed Reactive Power – kvar",
                            ObisCode = "1.0.3.7.0.255"
                        },
                        new
                        {
                            Id = 36,
                            Category = "Schedule",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Single Action Schedule for Billing Dates",
                            ObisCode = "0.0.15.0.0.255"
                        },
                        new
                        {
                            Id = 37,
                            Category = "Communication",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "TCP/UDP Setup",
                            ObisCode = "0.0.25.0.0.255"
                        },
                        new
                        {
                            Id = 38,
                            Category = "Communication",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "TCP/UDP Setup IPv4 Address",
                            ObisCode = "0.0.25.1.0.255"
                        },
                        new
                        {
                            Id = 39,
                            Category = "Communication",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "TCP/UDP Setup MAC Address",
                            ObisCode = "0.0.25.2.0.255"
                        },
                        new
                        {
                            Id = 40,
                            Category = "Event",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Transaction Related Event Code",
                            ObisCode = "0.0.96.11.3.255"
                        },
                        new
                        {
                            Id = 41,
                            Category = "Voltage",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Voltage – VBN",
                            ObisCode = "1.0.72.7.0.255"
                        },
                        new
                        {
                            Id = 42,
                            Category = "Voltage",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Voltage – VRN",
                            ObisCode = "1.0.32.7.0.255"
                        },
                        new
                        {
                            Id = 43,
                            Category = "Voltage",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Voltage – VYN",
                            ObisCode = "1.0.52.7.0.255"
                        });
                });

            modelBuilder.Entity("PQM.Core.Entities.ParameterValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int>("ParameterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ParameterValue");
                });

            modelBuilder.Entity("PQM.Core.Entities.ProfileCaptureObject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AttributeIndex")
                        .HasColumnType("int");

                    b.Property<string>("CaptureObisCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DataIndex")
                        .HasColumnType("int");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObisCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParameterId")
                        .HasColumnType("int");

                    b.Property<long>("ProfileGenericId")
                        .HasColumnType("bigint");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileGenericId", "DataIndex")
                        .IsUnique();

                    b.ToTable("ProfileCaptureObject");
                });

            modelBuilder.Entity("PQM.Core.Entities.ProfileData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("ObisCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParameterId")
                        .HasColumnType("int");

                    b.Property<long>("ProfileGenericId")
                        .HasColumnType("bigint");

                    b.Property<string>("RawDataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValuesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProfileData");
                });

            modelBuilder.Entity("PQM.Core.Entities.ProfileGeneric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CapturePeriod")
                        .HasColumnType("int");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastReadTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ObisCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ParameterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "ObisCode")
                        .IsUnique();

                    b.ToTable("ProfileGeneric");
                });

            modelBuilder.Entity("PQM.Core.Entities.RegisterValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("DisplayValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObisCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParameterId")
                        .HasColumnType("int");

                    b.Property<double?>("ParsedValue")
                        .HasColumnType("float");

                    b.Property<string>("RawValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReadTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Scaler")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RegisterValue");
                });

            modelBuilder.Entity("PQM.Core.Entities.ScriptAction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("ObisCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParameterId")
                        .HasColumnType("int");

                    b.Property<string>("ParameterValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScriptId")
                        .HasColumnType("int");

                    b.Property<long>("ScriptTableId")
                        .HasColumnType("bigint");

                    b.Property<int>("TargetIndex")
                        .HasColumnType("int");

                    b.Property<string>("TargetObisCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ScriptAction");
                });

            modelBuilder.Entity("PQM.Core.Entities.ScriptTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("ObisCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ParameterId")
                        .HasColumnType("int");

                    b.Property<string>("RawValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReadTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ScriptObisCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "ObisCode")
                        .IsUnique();

                    b.ToTable("ScriptTable");
                });

            modelBuilder.Entity("PQM.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
