// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PQM.Infrastructure;

#nullable disable

namespace PQM.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PQM.Core.Entities.ActionSchedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateEntered")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ActionSchedule");
                });

            modelBuilder.Entity("PQM.Core.Entities.ActivityCalendar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateEntered")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ActivityCalendar");
                });

            modelBuilder.Entity("PQM.Core.Entities.AssociationLogicalName", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateEntered")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AssociationLogicalName");
                });

            modelBuilder.Entity("PQM.Core.Entities.Clock", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateEntered")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clock");
                });

            modelBuilder.Entity("PQM.Core.Entities.ConnectedHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConnectedHeader");
                });

            modelBuilder.Entity("PQM.Core.Entities.DLMSObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HeaderId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObisCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DLMSObject");
                });

            modelBuilder.Entity("PQM.Core.Entities.Data", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateEntered")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Data");
                });

            modelBuilder.Entity("PQM.Core.Entities.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConnectionSettings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsumerNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedId")
                        .HasColumnType("int");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSync")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PORT")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Device");
                });

            modelBuilder.Entity("PQM.Core.Entities.DeviceLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateStamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<double?>("NumericValue")
                        .HasColumnType("float");

                    b.Property<int>("ParameterId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeviceLog");
                });

            modelBuilder.Entity("PQM.Core.Entities.DeviceLogSearch", b =>
                {
                    b.Property<DateTime>("DateStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("PQM.Core.Entities.DeviceParameterMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateStamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int>("ParameterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DeviceParameterMapping");
                });

            modelBuilder.Entity("PQM.Core.Entities.EventLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("A")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<double?>("Duration")
                        .HasColumnType("float");

                    b.Property<DateTime?>("End_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Max_Voltage")
                        .HasColumnType("float");

                    b.Property<double?>("Min_Voltage")
                        .HasColumnType("float");

                    b.Property<string>("Phase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Start_Time")
                        .HasColumnType("datetime2");

                    b.Property<double?>("UMAX")
                        .HasColumnType("float");

                    b.Property<double?>("USS")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("EventLog");
                });

            modelBuilder.Entity("PQM.Core.Entities.EventStatusMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BitIndex")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventCode")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObisCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EventStatusMapping");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BitIndex = 0,
                            Category = "voltage",
                            EventCode = 1,
                            Label = "R-Phase - Voltage Missing - Occurrence",
                            ObisCode = "0.0.96.11.0.255"
                        },
                        new
                        {
                            Id = 2,
                            BitIndex = 1,
                            Category = "voltage",
                            EventCode = 2,
                            Label = "R-Phase - Voltage Missing - Restoration",
                            ObisCode = "0.0.96.11.0.255"
                        },
                        new
                        {
                            Id = 3,
                            BitIndex = 2,
                            Category = "voltage",
                            EventCode = 3,
                            Label = "Y-Phase - Voltage Missing - Occurrence",
                            ObisCode = "0.0.96.11.0.255"
                        },
                        new
                        {
                            Id = 4,
                            BitIndex = 3,
                            Category = "voltage",
                            EventCode = 4,
                            Label = "Y-Phase - Voltage Missing - Restoration",
                            ObisCode = "0.0.96.11.0.255"
                        },
                        new
                        {
                            Id = 5,
                            BitIndex = 4,
                            Category = "voltage",
                            EventCode = 5,
                            Label = "B-Phase - Voltage Missing - Occurrence",
                            ObisCode = "0.0.96.11.0.255"
                        },
                        new
                        {
                            Id = 6,
                            BitIndex = 5,
                            Category = "voltage",
                            EventCode = 6,
                            Label = "B-Phase - Voltage Missing - Restoration",
                            ObisCode = "0.0.96.11.0.255"
                        },
                        new
                        {
                            Id = 7,
                            BitIndex = 6,
                            Category = "voltage",
                            EventCode = 7,
                            Label = "Over Voltage in any Phase - Occurrence",
                            ObisCode = "0.0.96.11.0.255"
                        },
                        new
                        {
                            Id = 8,
                            BitIndex = 7,
                            Category = "voltage",
                            EventCode = 8,
                            Label = "Over Voltage in any Phase - Restoration",
                            ObisCode = "0.0.96.11.0.255"
                        },
                        new
                        {
                            Id = 9,
                            BitIndex = 8,
                            Category = "voltage",
                            EventCode = 9,
                            Label = "Low Voltage in any Phase - Occurrence",
                            ObisCode = "0.0.96.11.0.255"
                        },
                        new
                        {
                            Id = 10,
                            BitIndex = 9,
                            Category = "voltage",
                            EventCode = 10,
                            Label = "Low Voltage in any Phase - Restoration",
                            ObisCode = "0.0.96.11.0.255"
                        },
                        new
                        {
                            Id = 11,
                            BitIndex = 10,
                            Category = "voltage",
                            EventCode = 11,
                            Label = "Voltage Unbalance - Occurrence",
                            ObisCode = "0.0.96.11.0.255"
                        },
                        new
                        {
                            Id = 12,
                            BitIndex = 11,
                            Category = "voltage",
                            EventCode = 12,
                            Label = "Voltage Unbalance - Restoration",
                            ObisCode = "0.0.96.11.0.255"
                        },
                        new
                        {
                            Id = 13,
                            BitIndex = 4,
                            Category = "current",
                            EventCode = 51,
                            Label = "R Phase - Current reverse - Occurrence",
                            ObisCode = "0.0.96.11.1.255"
                        },
                        new
                        {
                            Id = 14,
                            BitIndex = 5,
                            Category = "current",
                            EventCode = 52,
                            Label = "R Phase - Current reverse - Restoration",
                            ObisCode = "0.0.96.11.1.255"
                        },
                        new
                        {
                            Id = 15,
                            BitIndex = 8,
                            Category = "current",
                            EventCode = 53,
                            Label = "Y Phase - Current reverse - Occurrence",
                            ObisCode = "0.0.96.11.1.255"
                        },
                        new
                        {
                            Id = 16,
                            BitIndex = 9,
                            Category = "current",
                            EventCode = 54,
                            Label = "Y Phase - Current reverse - Restoration",
                            ObisCode = "0.0.96.11.1.255"
                        },
                        new
                        {
                            Id = 17,
                            BitIndex = 10,
                            Category = "current",
                            EventCode = 55,
                            Label = "B Phase - Current reverse - Occurrence",
                            ObisCode = "0.0.96.11.1.255"
                        },
                        new
                        {
                            Id = 18,
                            BitIndex = 11,
                            Category = "current",
                            EventCode = 56,
                            Label = "B Phase - Current reverse - Restoration",
                            ObisCode = "0.0.96.11.1.255"
                        },
                        new
                        {
                            Id = 19,
                            BitIndex = 7,
                            Category = "current",
                            EventCode = 63,
                            Label = "Current Unbalance - Occurrence",
                            ObisCode = "0.0.96.11.1.255"
                        },
                        new
                        {
                            Id = 20,
                            BitIndex = 6,
                            Category = "current",
                            EventCode = 64,
                            Label = "Current Unbalance - Restoration",
                            ObisCode = "0.0.96.11.1.255"
                        },
                        new
                        {
                            Id = 21,
                            BitIndex = 0,
                            Category = "current",
                            EventCode = 65,
                            Label = "Current bypass - Occurrence",
                            ObisCode = "0.0.96.11.1.255"
                        },
                        new
                        {
                            Id = 22,
                            BitIndex = 1,
                            Category = "current",
                            EventCode = 66,
                            Label = "Current bypass - Restoration",
                            ObisCode = "0.0.96.11.1.255"
                        },
                        new
                        {
                            Id = 23,
                            BitIndex = 2,
                            Category = "current",
                            EventCode = 67,
                            Label = "Over current in any phase - Occurrence",
                            ObisCode = "0.0.96.11.1.255"
                        },
                        new
                        {
                            Id = 24,
                            BitIndex = 3,
                            Category = "current",
                            EventCode = 68,
                            Label = "Over current in any phase - Restoration",
                            ObisCode = "0.0.96.11.1.255"
                        },
                        new
                        {
                            Id = 25,
                            BitIndex = 0,
                            Category = "power",
                            EventCode = 101,
                            Label = "Power failure - Occurrence",
                            ObisCode = "0.0.96.11.2.255"
                        },
                        new
                        {
                            Id = 26,
                            BitIndex = 1,
                            Category = "power",
                            EventCode = 102,
                            Label = "Power failure - Restoration",
                            ObisCode = "0.0.96.11.2.255"
                        },
                        new
                        {
                            Id = 27,
                            BitIndex = 0,
                            Category = "transaction",
                            EventCode = 151,
                            Label = "Real Time Clock - Date and Time",
                            ObisCode = "0.0.96.11.3.255"
                        },
                        new
                        {
                            Id = 28,
                            BitIndex = 1,
                            Category = "transaction",
                            EventCode = 152,
                            Label = "Demand Integration Period",
                            ObisCode = "0.0.96.11.3.255"
                        },
                        new
                        {
                            Id = 29,
                            BitIndex = 2,
                            Category = "transaction",
                            EventCode = 153,
                            Label = "Profile Capture Period",
                            ObisCode = "0.0.96.11.3.255"
                        },
                        new
                        {
                            Id = 30,
                            BitIndex = 3,
                            Category = "transaction",
                            EventCode = 154,
                            Label = "Single-action Schedule for Billing Dates",
                            ObisCode = "0.0.96.11.3.255"
                        },
                        new
                        {
                            Id = 31,
                            BitIndex = 4,
                            Category = "transaction",
                            EventCode = 155,
                            Label = "Activity Calendar Time Zones",
                            ObisCode = "0.0.96.11.3.255"
                        },
                        new
                        {
                            Id = 32,
                            BitIndex = 5,
                            Category = "transaction",
                            EventCode = 157,
                            Label = "New Firmware Activated",
                            ObisCode = "0.0.96.11.3.255"
                        },
                        new
                        {
                            Id = 33,
                            BitIndex = 6,
                            Category = "transaction",
                            EventCode = 158,
                            Label = "Load limit (kW) set",
                            ObisCode = "0.0.96.11.3.255"
                        },
                        new
                        {
                            Id = 34,
                            BitIndex = 7,
                            Category = "transaction",
                            EventCode = 159,
                            Label = "Enabled - load limit function",
                            ObisCode = "0.0.96.11.3.255"
                        },
                        new
                        {
                            Id = 35,
                            BitIndex = 8,
                            Category = "transaction",
                            EventCode = 160,
                            Label = "Disabled - load limit function",
                            ObisCode = "0.0.96.11.3.255"
                        },
                        new
                        {
                            Id = 36,
                            BitIndex = 9,
                            Category = "transaction",
                            EventCode = 161,
                            Label = "LLS secret (MR) change",
                            ObisCode = "0.0.96.11.3.255"
                        },
                        new
                        {
                            Id = 37,
                            BitIndex = 10,
                            Category = "transaction",
                            EventCode = 162,
                            Label = "HLS key (US) change",
                            ObisCode = "0.0.96.11.3.255"
                        },
                        new
                        {
                            Id = 38,
                            BitIndex = 11,
                            Category = "transaction",
                            EventCode = 163,
                            Label = "HLS key (FW) change",
                            ObisCode = "0.0.96.11.3.255"
                        },
                        new
                        {
                            Id = 39,
                            BitIndex = 12,
                            Category = "transaction",
                            EventCode = 164,
                            Label = "Global key change(encryption and authentication)",
                            ObisCode = "0.0.96.11.3.255"
                        },
                        new
                        {
                            Id = 40,
                            BitIndex = 13,
                            Category = "transaction",
                            EventCode = 165,
                            Label = "ESWF change",
                            ObisCode = "0.0.96.11.3.255"
                        },
                        new
                        {
                            Id = 41,
                            BitIndex = 14,
                            Category = "transaction",
                            EventCode = 166,
                            Label = "MD reset",
                            ObisCode = "0.0.96.11.3.255"
                        },
                        new
                        {
                            Id = 42,
                            BitIndex = 15,
                            Category = "transaction",
                            EventCode = 169,
                            Label = "Single Action Schedule for Image Activation",
                            ObisCode = "0.0.96.11.3.255"
                        },
                        new
                        {
                            Id = 43,
                            BitIndex = 16,
                            Category = "transaction",
                            EventCode = 182,
                            Label = "Passive Relay time.",
                            ObisCode = "0.0.96.11.3.255"
                        },
                        new
                        {
                            Id = 44,
                            BitIndex = 0,
                            Category = "others",
                            EventCode = 201,
                            Label = "Influence of permanent magnet - Occurrence",
                            ObisCode = "0.0.96.11.4.255"
                        },
                        new
                        {
                            Id = 45,
                            BitIndex = 1,
                            Category = "others",
                            EventCode = 202,
                            Label = "Influence of permanent magnet - Restoration",
                            ObisCode = "0.0.96.11.4.255"
                        },
                        new
                        {
                            Id = 46,
                            BitIndex = 2,
                            Category = "others",
                            EventCode = 203,
                            Label = "Neutral disturbance - Occurrence",
                            ObisCode = "0.0.96.11.4.255"
                        },
                        new
                        {
                            Id = 47,
                            BitIndex = 3,
                            Category = "others",
                            EventCode = 204,
                            Label = "Neutral disturbance - Restoration",
                            ObisCode = "0.0.96.11.4.255"
                        },
                        new
                        {
                            Id = 48,
                            BitIndex = 4,
                            Category = "others",
                            EventCode = 205,
                            Label = "Meter cover opened",
                            ObisCode = "0.0.96.11.4.255"
                        },
                        new
                        {
                            Id = 50,
                            BitIndex = 5,
                            Category = "others",
                            EventCode = 206,
                            Label = "Terminal cover opened",
                            ObisCode = "0.0.96.11.4.255"
                        });
                });

            modelBuilder.Entity("PQM.Core.Entities.FTPSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FtpHost")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RootFolderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FTPSetting");
                });

            modelBuilder.Entity("PQM.Core.Entities.IecHdlcSetup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateEntered")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IecHdlcSetup");
                });

            modelBuilder.Entity("PQM.Core.Entities.Ip4Setup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateEntered")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ip4Setup");
                });

            modelBuilder.Entity("PQM.Core.Entities.MacAddressSetup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateEntered")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MacAddressSetup");
                });

            modelBuilder.Entity("PQM.Core.Entities.ObjectParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AttributeId")
                        .HasColumnType("int");

                    b.Property<string>("DataType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ObjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ObjectParameter");
                });

            modelBuilder.Entity("PQM.Core.Entities.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Attribute3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObisCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Scaler")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Parameter");
                });

            modelBuilder.Entity("PQM.Core.Entities.ParameterValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ParameterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ParameterValue");
                });

            modelBuilder.Entity("PQM.Core.Entities.ProfileGeneric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateEntered")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProfileGeneric");
                });

            modelBuilder.Entity("PQM.Core.Entities.ProfileGenericEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("datetime2");

                    b.Property<double?>("NumericValue")
                        .HasColumnType("float");

                    b.Property<string>("ObisCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProfileGenericEntry");
                });

            modelBuilder.Entity("PQM.Core.Entities.Register", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateEntered")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("NumericValue")
                        .HasColumnType("float");

                    b.Property<string>("ObisCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Scaler")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Register");
                });

            modelBuilder.Entity("PQM.Core.Entities.ScriptTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateEntered")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ScriptTable");
                });

            modelBuilder.Entity("PQM.Core.Entities.TcpUdpSetup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateEntered")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TcpUdpSetup");
                });

            modelBuilder.Entity("PQM.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
