<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <!--<SpaRoot>..\pqm.client</SpaRoot>
    <SpaProxyLaunchCommand>npm run dev</SpaProxyLaunchCommand>
    <SpaProxyServerUrl>https://localhost:49904</SpaProxyServerUrl>-->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.SpaProxy">
      <Version>9.*-*</Version>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <!--<ProjectReference Include="..\pqm.client\pqm.client.esproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>-->
    <ProjectReference Include="..\PQM.Core\PQM.Core.csproj" />
    <ProjectReference Include="..\PQM.Infrastructure\PQM.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="D:\Projects\Compac\PQM\PQM.Server\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Controllers\DeviceController.cs~RF7335c64.TMP" />
  </ItemGroup>

  <ItemGroup>
    <None Include="D:\Projects\Compac\PQM\PQM.Server\.editorconfig" />
  </ItemGroup>

</Project>
